[package]
name = "matmul"
version = "0.1.0"
edition = "2021"

[package.metadata.maturin]
name = "madet._madet"

[lib]
crate-type = ["cdylib", "rlib"]
name = "madet"

[dependencies]
pyo3 = { version = "0.23.0", features = ["extension-module"] }

