[project]
name = "python_rust_demo"
classifiers = ["Programming Language :: Python"]

[tool.maturin]
python-source = "python"
module-name = "python_rust_demo._internal"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
